version: '3.8'
services:
  database:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - /data/configdb
    restart: always
  redis:
    container_name: redis
    hostname: redis_server
    image: redis:latest
    command: --port 6380
    ports:
      - '6380:6380'
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always

  api:
    container_name: explorer-backend
    build:
      dockerfile: Dockerfile
      context: './backend'
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    depends_on:
      - database
    ports:
      - 8888:8888
    environment:
      - PORT=${PORT}
      - HTTPS_ENDPOINT=${HTTPS_ENDPOINT}
      - PROJECT_ID=${PROJECT_SECRET}
      - PROJECT_SECRET=${PROJECT_ID}
      - UNISWAP_CONTRACT_ADDRESS=${UNISWAP_CONTRACT_ADDRESS}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - MONGO_CONNECTION_URI=${MONGO_CONNECTION_URI}
    restart: unless-stopped

  client:
    container_name: explorer-client
    build:
      dockerfile: Dockerfile
      context: './explorer-client'
    volumes:
      - /usr/src/app/node_modules
      - ./explorer-client:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: unless-stopped
volumes:
  redis-data: {}
